server:
  port: ${PORT:9011}

spring:
  application:
    name: shop-service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localserver:3306/cloudlearn?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  zipkin:
    base-url: http://127.0.0.1:9411 #zipkin server的请求地址
    sender:
      type: web  #数据的传输方式 , 以http的形式向server端发送数据
    sleuth:
      sampler:
        probability: 1 #采样比

eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册 在服务注册中心中显示真实的IP地址
#    lease-renewal-interval-in-seconds: 5 #向注册中心中注册服务id
#    lease-expiration-duration-in-seconds: 10 #续约到期的时间

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG