server:
  port: 8001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: provider-other
          uri: http://localhost:8091
          predicates:
            - Path=/provider-other/**
          filters:
            - RewritePath=/provider-other/(?<segment>.*), /$\{segment}
        - id: provider-consumer
          uri: lb://provider-consumer
          predicates:
            - Path=/provider-consumer/**
          filters:
            - RewritePath=/provider-consumer/(?<segment>.*), /$\{segment}
