server:
  port: ${PORT:7002}
spring:
  application:
    name: stream-consumer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      instanceCount: 2  #消费者总数
      instanceIndex: 1  #当前消费者的索引
      bindings:
        input: #通道名称 内置的获取消息的通道 , 从xiuming-stream中获取消息
          destination: xiuming-stream
        ming-input:
          destination: xiuming-stream-custom
          group: group1
          consumer:
            partitioned: true  #开启分区支持
