server:
  port: 9021

#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
spring:
  application:
    name: shop-service-order