server:
  port: 8032
spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://shop-service-order
          predicates:
            - Path=/shop-service-order/**
          filters:
            - RewritePath=/shop-service-order/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:8001/eureka/
      registry-fetch-interval-seconds: 5 # 获取服务列表的周期:5s
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG