server:
  port: 9022

#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
spring:
  application:
    name: shop-service-order-rest-hystrix


## 暴露所有的监控信息，该配置是actuator的
management:
  endpoints:
    web:
      exposure:
        include: '*'